apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitcoind.fullname" . }}
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "bitcoind.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bitcoind.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bitcoind.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.debug }}
          image: centos:8
          command: ['sleep']
          args: ['infinity']
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if not .Values.config.printtoconsole }}
            - "-printtoconsole=0"
            {{- end }}
            {{- if .Values.config.whitelist }}
            - "-whitelist={{ .Values.config.whitelist }}"
            {{- end }}
            - "-testnet={{ .Values.config.testnet }}"
            - "-listen=1"
            - "-server=1"
            {{- if gt (.Values.config.prune | toString | atoi) 0 }}
            - "-prune={{ .Values.config.prune }}"
            - "-txindex=0"
            {{- else }}
            - "-txindex=1"
            - "-blockfilterindex=1"            
            {{- end }}            
            - "-disablewallet=0"
            - "-dbcache=1024"
            - "-maxorphantx=10"
            - "-maxmempool=256"
            - "-maxconnections=20"
            - "-maxuploadtarget=5000"
            - "-rest=1"
            - "-rpcauth={{ .Values.config.rpcauth }}"
            - "-rpcbind=0.0.0.0"
            - "-rpcport=8332"
            - "-rpcallowip={{ .Values.config.rpc.allowip }}"
            - "-zmqpubrawblock=tcp://0.0.0.0:28332"
            - "-zmqpubrawtx=tcp://0.0.0.0:28333"
            {{- end }}
          env:
          - name: BITCOIN_DATA
            value: /data/
          volumeMounts:
          - mountPath: /data
            name: bitcoind
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: bitcoind
        persistentVolumeClaim:
          claimName: bitcoind
